#!/usr/bin/env python3
"""Generate the Codex adapters from the Claude ones.

Two agent-facing adapter sets for the same workflows is two places to correct
when a workflow changes, and the source repo's own guidance records the drift
that follows. So one set is authored and the other is DERIVED: edit
skills/<name>/SKILL.md and regenerate.

Usage:
    scripts/gen_adapters.py           # write adapters/codex/
    scripts/gen_adapters.py --check   # exit 1 if any file is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "skills"
DST = ROOT / "adapters" / "codex"

HEADER = """<!-- GENERATED by scripts/gen_adapters.py from skills/{name}/SKILL.md.
Do not edit: run the generator instead. The canonical workflow is
reference/{name}.md; this file only routes an agent to it. -->
"""


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        raise SystemExit("adapter has no frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SystemExit("adapter frontmatter is unterminated")
    return text[4:end], text[end + 5:]


def render(name: str, text: str) -> str:
    """Codex reads a repo-relative path, so ${CLAUDE_PLUGIN_ROOT} is rewritten.

    Codex has no plugin root: it discovers skills from the checkout. So the
    generated adapter points at the vendored copy the user installed, which is
    the one difference between the two sets and the reason this is a generator
    rather than a copy.
    """
    fm, body = split_frontmatter(text)
    # allowed-tools is Claude Code's key and means nothing to Codex; the rest
    # (name, description, argument-hint) carries over unchanged.
    kept = [ln for ln in fm.splitlines() if not ln.startswith("allowed-tools:")]
    body = body.replace("${CLAUDE_PLUGIN_ROOT}/", ".cadence/")
    return "---\n" + "\n".join(kept).strip() + "\n---\n\n" + HEADER.format(name=name) + body.lstrip("\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify freshness instead of writing")
    args = ap.parse_args()

    stale, written = [], 0
    for src in sorted(SRC.glob("*/SKILL.md")):
        name = src.parent.name
        want = render(name, src.read_text(encoding="utf-8"))
        out = DST / name / "SKILL.md"
        if args.check:
            if not out.exists() or out.read_text(encoding="utf-8") != want:
                stale.append(name)
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        if not out.exists() or out.read_text(encoding="utf-8") != want:
            out.write_text(want, encoding="utf-8")
            written += 1

    # A generated file with no source is worse than a stale one: it is a
    # workflow that quietly still exists for one agent after being removed.
    orphans = sorted(
        d.name for d in DST.glob("*") if d.is_dir() and not (SRC / d.name / "SKILL.md").exists()
    )
    if orphans:
        print(f"orphaned generated adapters (no matching skills/<name>/SKILL.md): {', '.join(orphans)}",
              file=sys.stderr)
        return 1

    if args.check:
        if stale:
            print(f"stale generated adapters: {', '.join(stale)}\nrun scripts/gen_adapters.py",
                  file=sys.stderr)
            return 1
        print(f"gen_adapters: {len(list(SRC.glob('*/SKILL.md')))} adapters up to date")
        return 0

    print(f"gen_adapters: wrote {written}, {len(list(SRC.glob('*/SKILL.md')))} total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
