#!/usr/bin/env python3
"""init_project.py - scaffold cadence's files into the current project.

This exists because the alternative is telling people a path. The templates
live inside the installed plugin, and that location is neither stable nor
guessable: it is version-pinned, it differs by install method, and a README
that hardcodes one is wrong for most readers and silently stale for the rest.

So nothing here asks the user where anything is. The script sits next to the
templates and finds them relative to itself.

Usage:
    init_project.py                  # cadence.toml
    init_project.py --retros         # also the retro ledger
    init_project.py --all            # everything, including optional templates
    init_project.py --dry-run        # print what would happen, touch nothing

Never overwrites. A file that already exists is reported as kept, because the
one thing worse than a missing config is a customized one silently replaced.

Exit codes:
    0  done, or nothing left to do
    1  could not find the templates, or could not write
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = PLUGIN_ROOT / "templates"

# Written into the project as .cadence/check-scope. Deliberately not a copy of
# fanout.py: a vendored copy goes stale silently, and the boundary check is the
# last thing that should be running an old version. This finds the installed
# plugin at run time and delegates.
DISPATCH = r"""#!/usr/bin/env bash
# Generated by cadence's init_project.py. Safe to commit.
#
# One entry point to the installed cadence plugin's tools, callable from a plain
# shell. It exists because the plugin's own path is version-pinned
# (~/.claude/plugins/cache/cadence/cadence/<version>/) and ${CLAUDE_PLUGIN_ROOT}
# is only set inside a skill — so neither can be written into a hook config, a
# Makefile, or a README. This resolves the plugin at run time instead.
#
#   ./.cadence/cadence config                 # effective configuration
#   ./.cadence/cadence config --json
#   ./.cadence/cadence must-stop <path>...    # exit 5 if inside the boundary
#   ./.cadence/cadence check-scope            # the fan-out commit gate
#   ./.cadence/cadence fanout <args>          # the fan-out engine
#   ./.cadence/cadence review-state --pr <n>  # honest review state
#   ./.cadence/cadence spec-hash spec <file>
#   ./.cadence/cadence ask <args>
set -euo pipefail

if [ -n "${CADENCE_PLUGIN_ROOT:-}" ]; then
  root="$CADENCE_PLUGIN_ROOT"
else
  # Newest installed version wins. `sort -V` so 0.10.0 beats 0.9.0.
  root="$(find "$HOME/.claude/plugins" -maxdepth 5 -type d -name tools -path '*cadence*' 2>/dev/null \
          | sed 's|/tools$||' | sort -V | tail -1)"
fi

if [ -z "${root:-}" ] || [ ! -d "$root/tools" ]; then
  echo "cadence: could not find the installed plugin." >&2
  echo "  Install it:  /plugin marketplace add arbor-ai-inc/cadence" >&2
  echo "               /plugin install cadence@cadence" >&2
  echo "  Or set CADENCE_PLUGIN_ROOT to the plugin directory." >&2
  echo >&2
  echo "  NOTE: if a commit hook calls this, the must-stop boundary is NOT" >&2
  echo "  being enforced until it works — which looks identical to working." >&2
  exit 1
fi

cmd="${1:-}"; shift || true
case "$cmd" in
  config)       exec python3 "$root/tools/cadence_config.py" "$@" ;;
  must-stop)    exec python3 "$root/tools/cadence_config.py" must-stop "$@" ;;
  check-scope)  exec python3 "$root/tools/fanout.py" check-scope "$@" ;;
  fanout)       exec python3 "$root/tools/fanout.py" "$@" ;;
  review-state) exec python3 "$root/tools/review_state.py" "$@" ;;
  spec-hash)    exec python3 "$root/tools/spec_hash.py" "$@" ;;
  ask)          exec python3 "$root/tools/ask.py" "$@" ;;
  init)         exec python3 "$root/tools/init_project.py" "$@" ;;
  ""|-h|--help)
    sed -n '4,20p' "$0" | sed 's/^# \{0,1\}//'
    exit 0 ;;
  *)
    echo "cadence: unknown command '$cmd'. Run with --help." >&2
    exit 1 ;;
esac
"""

# Kept separate so a hook config that already points at .cadence/check-scope
# keeps working. Removing it would silently disable somebody's boundary gate.
SHIM = r"""#!/usr/bin/env bash
# Generated by cadence's init_project.py. Safe to commit.
# Thin alias for `./.cadence/cadence check-scope`, kept so existing hook
# configs keep working.
set -euo pipefail
exec "$(dirname "$0")/cadence" check-scope "$@"
"""


def project_root(start: Path | None = None) -> Path:
    """The repo root, so running this from a subdirectory still does the right thing."""
    cwd = Path(start or Path.cwd()).resolve()
    try:
        out = subprocess.run(
            ["git", "-C", str(cwd), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        return Path(out)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return cwd


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--retros", action="store_true", help="also create the retro ledger")
    ap.add_argument("--all", action="store_true", help="everything, including the optional templates")
    ap.add_argument("--dry-run", action="store_true", help="print what would happen; write nothing")
    ap.add_argument("--hook", action="store_true",
                    help="also write .cadence/check-scope, a shim a commit hook can call")
    ap.add_argument("--into", type=Path, help="target project root (default: the enclosing git repo)")
    args = ap.parse_args()

    if not TEMPLATES.is_dir():
        print(f"init_project: no templates at {TEMPLATES}. Is the plugin installed intact?",
              file=sys.stderr)
        return 1

    root = (args.into or project_root()).resolve()
    retros = args.retros or args.all

    # (source relative to templates/, destination relative to project root)
    plan: list[tuple[str, str]] = [("cadence.toml", "cadence.toml")]
    if retros:
        plan += [
            ("TRAPS.md", "docs/retros/TRAPS.md"),
            ("_fragment_template.md", "docs/retros/_fragment_template.md"),
        ]
    if args.all:
        plan += [
            ("architectural-principles.starter.md", "docs/architectural-principles.md"),
            ("code-review-standards.template.md", "docs/code-review-standards.md"),
            ("tools-and-services.template.md", "docs/tools-and-services.md"),
            ("_product_template.md", "specs/_product_template.md"),
            ("_design_template.md", "specs/_design_template.md"),
        ]

    created, kept, missing = [], [], []
    for src_name, dst_rel in plan:
        src, dst = TEMPLATES / src_name, root / dst_rel
        if not src.exists():
            missing.append(src_name)
            continue
        if dst.exists():
            kept.append(dst_rel)
            continue
        created.append(dst_rel)
        if not args.dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)

    # A commit hook runs in a plain shell, where ${CLAUDE_PLUGIN_ROOT} is NOT
    # set, and the installed path is version-pinned (.../cadence/0.1.0/...) so
    # hardcoding it breaks on the next release. Neither is usable in a hook.
    #
    # So write a shim INTO the project. It resolves the plugin at run time and
    # the hook config points at a stable in-repo path.
    dispatch = root / ".cadence" / "cadence"
    if dispatch.exists():
        kept.append(".cadence/cadence")
    else:
        created.append(".cadence/cadence")
        if not args.dry_run:
            dispatch.parent.mkdir(parents=True, exist_ok=True)
            dispatch.write_text(DISPATCH)
            dispatch.chmod(0o755)

    shim_written = False
    if args.hook or args.all:
        shim = root / ".cadence" / "check-scope"
        if shim.exists():
            kept.append(".cadence/check-scope")
        else:
            shim_written = True
            if not args.dry_run:
                shim.parent.mkdir(parents=True, exist_ok=True)
                shim.write_text(SHIM)
                shim.chmod(0o755)
            created.append(".cadence/check-scope")

    dirs = []
    if retros:
        for d in ("docs/retros/pending", "docs/retros/archive"):
            keep = root / d / ".gitkeep"
            if keep.exists():
                kept.append(f"{d}/.gitkeep")
                continue
            dirs.append(d)
            if not args.dry_run:
                keep.parent.mkdir(parents=True, exist_ok=True)
                keep.touch()

    verb = "would create" if args.dry_run else "created"
    print(f"project: {root}\n")
    for path in created:
        print(f"  {verb}  {path}")
    for d in dirs:
        print(f"  {verb}  {d}/.gitkeep")
    for path in kept:
        print(f"  kept     {path}  (already there — not overwritten)")
    if missing:
        print(f"\n  MISSING from the plugin: {', '.join(missing)}", file=sys.stderr)

    if not created and not dirs:
        print("\nNothing to do — everything is already in place.")
        return 0
    if args.dry_run:
        print("\nDry run. Re-run without --dry-run to write.")
        return 0

    print("\nNext, and this is the part that matters:\n")
    if "cadence.toml" in created:
        print("  1. Edit cadence.toml and set [commands].lint and [commands].test.")
        print("     Put the WHOLE command in — venv activation, env vars, filters.")
        print("     Cadence runs them verbatim.\n")
        print("  2. Fill in [[must_stop]] before letting anything run unattended.")
        print("     It is the list of places an agent must stop and ask instead of")
        print("     deciding. Cadence ships none, because only you know yours — and")
        print("     an empty boundary means a run never stops for a human.\n")
    if retros and any(p.startswith("docs/retros") for p in created):
        print("  3. From now on, every PR leaves one fragment in docs/retros/pending/.")
        print("     At the threshold, run /cadence:retro-synthesis. Write no rules")
        print("     before then, however general a lesson feels.\n")
    if shim_written:
        print("  Wrote .cadence/check-scope. Point a pre-commit hook at it:\n")
        print("      entry: ./.cadence/check-scope")
        print("      language: system")
        print("      pass_filenames: false")
        print("      always_run: true\n")
        print("  Until that hook runs, the must-stop boundary is NOT enforced,")
        print("  and that looks identical to working from inside a run.\n")
    print("  Check it loaded:  python3 " + str(PLUGIN_ROOT / "tools" / "cadence_config.py"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
