#!/usr/bin/env python3
"""wrappers.py - render cadence's skills and agents for a project that vendors it.

The plugin gives every skill a `cadence:` prefix, and Codex cannot load a plugin
at all. A project that wants today's skill names, or Codex, vendors cadence at
.cadence/ (a git submodule, say) and gets thin wrappers generated from it:

  .claude/skills/<name>/SKILL.md   Claude Code, unprefixed
  .codex/skills/<name>/SKILL.md    Codex
  .claude/agents/<name>.md         the bundled subagents, unprefixed

Every wrapper points at the vendored copy, so the workflow text still has one
home. The wrappers are GENERATED: `--check` fails if any of them differs from
what the vendored copy would generate now, which is how a project keeps a
hand-edit (or a submodule bump nobody regenerated after) from passing CI.

A file at a wrapper's path that this did not generate is the project's own and
is never overwritten. It is reported, and the run fails, because a project skill
silently shadowing a cadence one is the drift this exists to prevent.

Usage (from the project):
    python3 .cadence/tools/wrappers.py --targets claude,codex
    python3 .cadence/tools/wrappers.py --targets claude,codex --check

Exit codes:
    0  wrappers written, or up to date
    1  stale, orphaned or conflicting wrappers, or a usage error
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PLUGIN_ROOT / "tools"))
import cadence_config  # noqa: E402

VENDOR_DIR = ".cadence"

# Not wrapped: `init` would shadow Claude Code's built-in /init, and a vendored
# project runs tools/init_project.py directly anyway.
SKIP_SKILLS = {"init"}

# What makes a file ours to rewrite or delete: this exact line, first in the
# body right after the frontmatter, naming a source inside the vendored copy.
# Matching the phrase anywhere would claim a project file that merely mentions
# it, or a project's own variant copied from a wrapper.
MARKER = "<!-- GENERATED by cadence from " + VENDOR_DIR + "/"

HEADER = """{marker}{src}.
Do not edit: regenerate instead. The canonical workflow is in the vendored
cadence copy; this file only routes an agent to it. -->

**Paths here.** This project vendors cadence at `.cadence/`. Where a cadence doc
names a path under the plugin root, it is under `.cadence/` here, and a
`cadence:`-prefixed skill is the unprefixed one.

"""

OVERLAY = """
**Project overlay.** After the canonical doc, read `{path}` if it exists.
It adds this project's rules to this workflow; it never removes or relaxes the
ones above.
"""

TARGETS = {
    # target: (skills dir, keep Claude-only frontmatter keys)
    "claude": (".claude/skills", True),
    "codex": (".codex/skills", False),
}
AGENTS_DIR = ".claude/agents"


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        raise SystemExit("source has no frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SystemExit("source frontmatter is unterminated")
    return text[4:end], text[end + 5:]


def render(text: str, src: str, root_prefix: str, keep_claude_keys: bool,
           overlay: str | None = None, model: str | None = None) -> str:
    """One wrapper: frontmatter, a generated-file header, the body re-rooted.

    ${CLAUDE_PLUGIN_ROOT} only expands inside a plugin, so the body is rewritten
    to point at `root_prefix` instead, and /cadence:<skill> becomes /<skill>.
    allowed-tools is Claude Code's key and
    means nothing to Codex; everything else carries over unchanged.

    `model` is the project's pin from [models.pins], Claude-only like
    allowed-tools. Cadence ships no pins; a project that vendors it may want
    its reviewers on one model and its implementer on another.
    """
    fm, body = split_frontmatter(text)
    lines = fm.splitlines()
    if not keep_claude_keys:
        lines = [ln for ln in lines if not ln.startswith("allowed-tools:")]
    elif model:
        lines = [ln for ln in lines if not ln.startswith("model:")] + [f"model: {model}"]
    body = body.replace("${CLAUDE_PLUGIN_ROOT}/", root_prefix)
    # The whole point of a wrapper is the unprefixed name, so a cross-reference
    # to /cadence:<skill> becomes /<skill>, in the description too.
    lines = [ln.replace("/cadence:", "/") for ln in lines]
    body = body.replace("/cadence:", "/")
    out = ("---\n" + "\n".join(lines).strip() + "\n---\n\n"
           + HEADER.format(marker=MARKER, src=src[len(VENDOR_DIR) + 1:]) + body.lstrip("\n"))
    if overlay:
        out = out.rstrip("\n") + "\n" + OVERLAY.format(path=overlay)
    return out


def planned(project: Path, targets: list[str], overlays: str | None,
            pins: dict | None = None) -> dict[Path, str]:
    """Every wrapper path in the project, and the content it should have."""
    prefix = VENDOR_DIR + "/"
    pins = pins or {}
    want: dict[Path, str] = {}
    for src in sorted((PLUGIN_ROOT / "skills").glob("*/SKILL.md")):
        name = src.parent.name
        if name in SKIP_SKILLS:
            continue
        text = src.read_text(encoding="utf-8")
        overlay = f"{overlays.rstrip('/')}/{name}.md" if overlays else None
        for t in targets:
            base, keep = TARGETS[t]
            want[project / base / name / "SKILL.md"] = render(
                text, f"{VENDOR_DIR}/skills/{name}/SKILL.md", prefix, keep, overlay, pins.get(name))
    if "claude" in targets:
        for src in sorted((PLUGIN_ROOT / "agents").glob("*.md")):
            overlay = f"{overlays.rstrip('/')}/{src.stem}.md" if overlays else None
            want[project / AGENTS_DIR / src.name] = render(
                src.read_text(encoding="utf-8"), f"{VENDOR_DIR}/agents/{src.name}",
                prefix, True, overlay, pins.get(src.stem))
    return want


def is_generated(text: str) -> bool:
    try:
        _fm, body = split_frontmatter(text)
    except SystemExit:
        return False
    return body.lstrip("\n").startswith(MARKER)


def generated_files(project: Path) -> list[Path]:
    """Wrappers already in the project that we generated, for EVERY target.

    Every target, not only the ones asked for this run: dropping codex from
    --targets must remove the codex wrappers, not leave them stale forever.
    """
    found = []
    for d in [base for base, _keep in TARGETS.values()] + [AGENTS_DIR]:
        base = project / d
        if not base.is_dir():
            continue
        candidates = base.glob("*.md") if d == AGENTS_DIR else base.glob("*/SKILL.md")
        for f in candidates:
            if is_generated(f.read_text(encoding="utf-8", errors="replace")):
                found.append(f)
    return sorted(found)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--targets", default="claude,codex",
                    help="comma-separated: claude, codex (default: both)")
    ap.add_argument("--check", action="store_true", help="verify freshness; write nothing")
    ap.add_argument("--into", type=Path, help="project root (default: the enclosing git repo)")
    args = ap.parse_args(argv)

    targets = [t.strip() for t in args.targets.split(",") if t.strip()]
    bad = [t for t in targets if t not in TARGETS]
    if bad or not targets:
        print(f"wrappers: unknown target(s) {', '.join(bad) or '(none)'}; use {', '.join(TARGETS)}",
              file=sys.stderr)
        return 1

    try:
        cfg = cadence_config.load(args.into)
    except cadence_config.ConfigError as exc:
        print(f"wrappers: {exc}", file=sys.stderr)
        return 1
    project = (args.into or cfg.root).resolve()

    # A wrapper that points at .cadence/ only works if cadence is there.
    vendored = project / VENDOR_DIR
    if vendored.resolve() != PLUGIN_ROOT:
        print(f"wrappers: run this from the vendored copy at {vendored}/tools/wrappers.py.\n"
              f"  This copy is at {PLUGIN_ROOT}, and the wrappers it wrote would point\n"
              f"  at a {VENDOR_DIR}/ that does not hold it.", file=sys.stderr)
        return 1

    # A pin naming no skill or agent is a typo that would silently pin nothing.
    names = {p.parent.name for p in (PLUGIN_ROOT / "skills").glob("*/SKILL.md")} - SKIP_SKILLS
    names |= {p.stem for p in (PLUGIN_ROOT / "agents").glob("*.md")}
    unknown = sorted(set(cfg.model_pins) - names)
    if unknown:
        print(f"wrappers: [models.pins] names {', '.join(unknown)}, which is no cadence "
              f"skill or agent. Known: {', '.join(sorted(names))}", file=sys.stderr)
        return 1

    want = planned(project, targets, cfg.overlays_dir, cfg.model_pins)
    stale, conflicts, written = [], [], []
    for path, content in want.items():
        rel = path.relative_to(project).as_posix()
        if path.exists():
            have = path.read_text(encoding="utf-8")
            if not is_generated(have):
                conflicts.append(rel)
                continue
            if have == content:
                continue
        stale.append(rel)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(rel)

    # A generated wrapper with no source is worse than a stale one: a workflow
    # that quietly still exists for one agent after cadence removed it.
    orphans = [f for f in generated_files(project) if f not in want]
    for f in orphans:
        if not args.check:
            f.unlink()
            if f.name == "SKILL.md" and not any(f.parent.iterdir()):
                f.parent.rmdir()

    for rel in conflicts:
        print(f"wrappers: {rel} exists and was not generated by cadence; kept.\n"
              f"  It shadows the cadence workflow of the same name. Remove it, or\n"
              f"  rename it if it is a different workflow.", file=sys.stderr)

    if args.check:
        problems = [f"stale: {r}" for r in stale]
        problems += [f"orphaned: {f.relative_to(project).as_posix()}" for f in orphans]
        for p in problems:
            print(f"wrappers: {p}", file=sys.stderr)
        if problems:
            print(f"wrappers: run  python3 {VENDOR_DIR}/tools/wrappers.py --targets {','.join(targets)}",
                  file=sys.stderr)
        if problems or conflicts:
            return 1
        print(f"wrappers: {len(want)} up to date")
        return 0

    print(f"wrappers: wrote {len(written)}, removed {len(orphans)} orphaned, {len(want)} total")
    return 1 if conflicts else 0


if __name__ == "__main__":
    sys.exit(main())
